### ISSUE TITLE
Bring Achilles package up-to-date with OHDSI standards

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Achilles#133]
We've learned a lot since the Achilles package was originally developed. It would be good to bring Achilles up-to-date with the current standards. Here are things that need to change:
- Create an `extras` folder in the package root
- Test code (e.g. TestAchillesCode.R) should be moved to this extras folder
- Add PackageMaintenance.R to extras folder for generating manual PDF and code-formatting (e.g. https://github.com/OHDSI/DatabaseConnector/blob/master/extras/PackageMaintenance.R)
- Generate manual PDF into the extras folder
- Run `OhdsiRTools::updateCopyrightYearFolder()` to update copyright notice year
- Add ^.travis.yml$ to .Rbuildignore
- Readme file doesn't adhere to OHDSI standard (see e.g. https://github.com/OHDSI/CohortMethod/blob/master/README.md )
- Description file: SqlRender and rjson should move from Depends to Imports (when in Imports they are no longer placed on the search path, so this is cleaner)
- Description file: Need better Description (more than 1 line)
- Description file: need to add Chris as author (and maintainer?)
- References to functions in packages in the Imports section should explicitly mention the package, e.g. `SqlRender::loadRenderTranslateSql()`
- Add missing function documentation (e.g. for achillesHeel function)
- I think data\allReports.rda is no longer needed because we now have inst\csv\analysisDetails.csv, so delete if possible (also remove entry from Achilles-package.R)
- R Check generates Warnings and Notes. Please clear all of those
- Add a vignette? (Not sure this is useful)

Furthermore, but this is probably nitpicking: we use camelCase in R, and snake_case in SQL (because most SQL dialects are case-insensitive). Usually after fetching the data from the server we immediately call

``` r
colnames(myData) <- SqlRender::snakeCaseToCamelCase(colnames(myData))
```

to convert the column names to camel case, and only use camel case in our R code. I'm surprised Achilles is actually working on non-SQL Server platforms, because not all platforms return field names in upper case.

**Comment by t-abdul-basser** [comment]
Thanks @schuemie. This is very helpful list. I reviewed in quickyl and they all make sense to me. I agree that this is a good time to do a review and apply some of these best practices and code standards. I would be happy to contribute to performing some of this clean up. Lets us know in this thread if anything else of this nature comes to mind.

**Comment by chrisknoll** [comment]
Thanks for putting this all together @schuemie .  I have one nitpick about your nitpick:  the case-sensitivity of columns in a select.  I did some googling, and I can't find a case where the default behavior of a DBMS is to have case sensitive column names:  Now, you can put 'quoted identifiers' in your CREATE TABLE statements to make the column names case sensitive (ie: you have to use the same quoted identifiers in your select statements) but we don't do that in any of our SQL.

I'm not sure where the idea that columns are case sensitive came form, but I believe you put something in the db connector package that does a UCASE or LCASE to the result column names that I think i've run into this (very painfully I might add) where i have a sql statement like this:

conceptData <- querySql(con, "select concept_id from concept where concept_id = 77")

# this fails:
conceptData$concept_id

#this works
conceptData$CONCEPT_ID

Does this ring a bell?  In any case, I'm not in favor of anything that transparently rewrites the result columns where i write one select one way and have to look for different column names when I'm reading the results. It's just confusing and headache-inducing.

Otherwise all your main bullet points are spot on and I think should be addressed.  Except putting me as maintainer, that's a an opening looking to be filled.

-Chris

**Comment by schuemie** [comment]
Hi Chris,

I meant that all DBMSs are case-insensitive, but I know that at least PostgreSQL stores its table and field names as lower case. I see now that despite this fact, the column names come in as upper case when using DatabaseConnector, so that's ok.

You may not like using 'different' names when querying the data compared to when using it in R, but it is what I have done in every other package. Else you have to maintain a hodgepodge of naming conventions throughout your R code. 'Where did this variable originate 10 steps ago? A database? Oh, in that case I have to use upper case snake_case. Oh wait, I transformed it in step 8, so now it should be snakeCase' Is a bit weird you'll have to admit.

The transformation of names is completely deterministic, so maybe not that much of a headache?

**Comment by chrisknoll** [comment]
Yeah, i was thinking about this further: if you were to use a JDBC resultset call: getString(columnName), the docs say it's case insensitive and it will find a column name with mixed case.  however, we're generating a R dataframe which exposes the column names as properties of the object, so R _is_ case sensitive so dataFrame$column1 is not the same as dataFrame$COLUMN1....so the whole case sensitivity issue stems from how R wraps a result set, not the case sensitivity of the database column names.  

So, that being said, a decision should be made about how to represent the the results of a query in a case-sensitive context like R.  This raises a question:  what will the resulting dataframe be for this query:

~~~sql
select domain_id, count(concept_id) as ConceptCount from CONCEPT
~~~~

What is the default behavior of the data frame when you executeQuery() vs. if you transform those column names into CamelCase?  I assume the default result will be DOMAIN_ID, CONCEPTCOUNT, and camelcase will be DomainId, Conceptcount.

**Comment by chrisknoll** [comment]
@schuemie , thinking about it even more: if there has to be some column-name standardization (either UCASE or lCASE) or something that is applied to the column names that are comming back into the dataframe, I guess making it camelcase is the 'best looking' approach since you have to be aware that what you put in the select may not be what you look for in the R dataframe anyways.  So, I guess I'm saying that I'm behind your idea, but this will be a pretty significan impact to AchillesWeb because the export simply executes the query and drops the resulting dataframe right in the exported object. If we camel case it, we'll have to go to the front end code and look for the new column names.  Painful, but I agree with the notion of standard conventions.

**Comment by schuemie** [comment]
@chrisknoll , I hadn't thought about downstream (AchillesWeb). I have no opinion on what happens there (in JavaScript). Ideally, you would stick to whatever standard you've declared there, and transform from one standard to the other if necessary at the point of interface. 

Given that not much processing is done in the Achilles R package, there is something to be said for leaving things as they are ;-)

**Comment by schuemie** [comment]
Oh, in response to your earlier question, calling

```sql
select domain_id, count(concept_id) as ConceptCount from CONCEPT
```
will result (after calling [snakeCaseToCamelCase](https://github.com/OHDSI/SqlRender/blob/master/R/HelperFunctions.R#L207)) in domainId, conceptcount.

**Comment by vojtechhuser** [comment]
The case sensitivity of R is a problem I also ran into. 

Knowing what to use in any SQL code and what in any R code would be very useful.

**Comment by vojtechhuser** [comment]
I was trying to fix some of the R documentation issues. 



The problem I have is that I have to install the package with option `install.packages(“SqlRender”,INSTALL_opts=“–no-multiarch”`
see here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:r_setup

R CMD fails since I have to somehow tell R to also do no-multiarch inside R package Check. Am I the only user who runs into that? (windows OS, 64 bit).

**Comment by schuemie** [comment]
Why not run Check using the `--no-multiarch` option? (RStudio --> Build --> More --> Configure build tools --> R CMD check additional options)

Most people seem to have both 32-bit and 64-bit Java installed, so don't need the –no-multiarch option for SqlRender.

**Comment by schuemie** [comment]
Just a reminder: SqlRender is currently still in the [Depends section in the DESCRIPTION file](https://github.com/OHDSI/Achilles/blob/master/DESCRIPTION#L21), meaning it is not only required to run Achilles, but is also loaded on the user's search path. I don't think that is really necessary, since users aren't expected to call SqlRender functions themselves. (Note that DatabaseConnector is a different story, since users must call createConnectionDetails to use Achilles). I recommend moving SqlRender to the Imports section instead.

**Comment by schuemie** [comment]
Another reminder: there are still WARNINGS and NOTES in the R checkout output:

```
* checking R code for possible problems ... NOTE
.deleteExistingResults: no visible binding for global variable
  ‘resultsDatabaseSchema’
achillesHeel: no visible binding for global variable
  ‘tempAchillesPrefix’
Undefined global functions or variables:
  resultsDatabaseSchema tempAchillesPrefix
```

```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'addDataSource'
  ‘dataSourcesFileName’
Documented arguments not in \usage in documentation object 'addDataSource':
  ‘dataSourcesFilename’
```

```
* checking installed files from ‘inst/doc’ ... NOTE
The following files should probably not be installed:
  ‘achilles_flowchart.png’, ‘logging_screenshot.png’,
  ‘shinyHeel_screenshot.png’
Consider the use of a .Rinstignore file: see ‘Writing R Extensions’,
or move the vignette sources from ‘inst/doc’ to ‘vignettes’.
```

I recommend clearing those. Once achieved, you can remove this [badge of shame](https://github.com/OHDSI/Achilles/blob/master/.travis.yml#L4) from your travis.yml ;-)

**Comment by t-abdul-basser** [comment]
Agreed. Will do :)

**Comment by t-abdul-basser** [comment]
Adding checklist. @alondhe  and @vojtechhuser have addressed several of these. Other are in progress for 1.7 release or not longer applicable.
 
- [ ] Create an extras folder in the package root
- [ ] Move Test code (e.g. TestAchillesCode.R) to `extras` folder
- [ ] Add PackageMaintenance.R to extras folder for generating manual PDF and code-formatting (e.g. https://github.com/OHDSI/DatabaseConnector/blob/master/extras/PackageMaintenance.R)
- [ ] Generate manual PDF into the extras folder
- [ ] Run OhdsiRTools::updateCopyrightYearFolder() to update copyright notice year
- [ ] Add ^.travis.yml$ to .Rbuildignore
- [ ] Modify Readme file so that it adhere to OHDSI standard (see e.g. https://github.com/OHDSI/CohortMethod/blob/master/README.md )
- [ ] Move SqlRender and rjson in Description file from Depends to Imports
- [ ] Add better Description file (more than 1 line)
- [ ] Add Chris as author in Description file
- [ ] Insure that references to functions in packages in the Imports section explicitly mention the package, e.g. SqlRender::loadRenderTranslateSql()
- [ ] Add missing function documentation (e.g. for achillesHeel function)
- [ ] Delete if possible data\allReports.rda since it is no longer needed (we now have inst\csv\analysisDetails.csv) and remove entry from Achilles-package.R)
- [ ] Clear R Check Warnings and Notes
- [ ] Add a vignette (if useful)

**Comment by t-abdul-basser** [comment]
Thanks @fdefalco!
