### ISSUE TITLE
analysis_name typo?

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Achilles#179]
I have spent almost no time with Achilles so far, so maybe this is intentional, but it looks like a typo to me: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/Achilles_v5.sql#L1159

    analysis_name: 'Number of measurement occurrence records, by observation_concept_id'
    stratum_1_name: 'measurement_concept_id'

(also see https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/Achilles_v5.sql#L6867)

If it is a mistake, I think there are some other analyses with the same mistake.

**Comment by chrisknoll** [comment]
I'm sorry, I must be missing somethign: what is the typo?

**Comment by Sigfried** [comment]
Shouldn't the analysis_name be 'Number of measurement occurrence records, by measurement_concept_id'?

**Comment by chrisknoll** [comment]
Yes, that looks like it should read '..., by measurement_concept_id'.

**Comment by t-abdul-basser** [comment]
Yes, the names of the analyses need to be revised generally for clarity. I think that this has been noted in an issue elsewhere. I propose that I work with @vojtechhuser to revise them before the next release.

**Comment by vojtechhuser** [comment]
I know about those typos. 
But since I caused issues with the capital column names in  a related file (updated via my package maintenance code) - I try to do minimal changes to that.  The code to update them is here. That code also contains my proposal to eliminate the insert into statements from the .sql file and use the new functionality of insertTable function.
https://github.com/OHDSI/Achilles/blob/master/extras/notes.md#update-csv-overview-file-for-analyses
