### ISSUE TITLE
Evaluation of some Heel Rules in R

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#246]
Heel SQL for all possible dialects is getting quite hard to write. (see forum post http://forums.ohdsi.org/t/ideas-for-sqlrender-2/932/37 

I am proposing to allow 2 modes of Heel rules.

One in SQL (now) and one in R directly. (not used as of now)

We load some Achilles results  data into memory (if it is small, under 50000 rows or so) - and do Heel logic in R.

SQL is nice, I love it -  but we are ending up with lots of "parametized SQL conventions" - and it can be error prone and tedious.

**Comment by t-abdul-basser** [comment]
@vojtechhuser Although this is certainly something that we can discuss. I would not advise going in this direction given the depth of investment in the current strategy--not only for Achilles but also for other OHDSI components; that it is not clear to me that moving to R would be worth it; that a mixed-SQL-and-R approach would be, in some ways, less maintainable and flexible. Coming to grips with differences between SQL dialects can be challenging but using R for this purpose doe snot seem to me to be the way to go.

**Comment by vojtechhuser** [comment]
What others think? @alondhe

**Comment by alondhe** [comment]
I agree with @t-abdul-basser here. To ensure there are no hurdles for any newcomer, it'd best if Achilles R package sticks to generating SQL that it can then run, or export for manual execution.

**Comment by vojtechhuser** [comment]
Hmm... So trying to downplay R code and possibly eliminating it?

I think the R component is quite useful and don't see why R could not be used more.
Given so many SQL dialects and rendering issues - R seems to be a safer and more developer friendly way to Heel logic.

**Comment by cgreich** [comment]
@alondhe, @t-abdul-basser: 

Aren't you guys (somebody) implement the generic execution engine? Which takes R or SQL no matter what? Let's push this forward. The SQL flavors are bugging us all over the place (ask Thomas across the corridor), and R doesn't have that problem.

**Comment by chrisknoll** [comment]
Yes, we have sqlrender, but you still have to adhere to some simple rules (such as JOIN clauses should have ON specified).  

Do you guys realize that if you want to do some operation in R, you need to pull it all into the local memory? So if you're interested in reporting a statistic on the median length of say across the 20 billion visits in your datastore, you'll need to download 20 billion length of stay values, sort them, and find the one that lands right in the middle?

We do things in the SQL context for a reason.  Just because it takes some skill to do it correctly, doesn't make it inferior.  Of course there are examples of doing certain things in a more straightforward manner, but we don't want to mix-and-match R implementations with Sql implementations if we can avoid it.

And if the suggestion is having 2 implementations of the analysis code (one in SQL one in R) who's going to keep those 2 implementations in sync?

To be clear: no one is preventing anyone from starting their own R-library using whatever approach they are most comfortable with.   On this point, I'd say to @vojtechhuser : if you do not want to use SQL, and you are unable to maintain the code you've contributed to Achilles (there are outstanding bugs with your enhancements that are waiting for you to fix), then I'd recommend removing those features from Achilles and create a separate auxiliary library that you can write in whatever language you are comfortable with.  We can then incorporate it into Achilles once it is stable and verified to be usable.

**Comment by vojtechhuser** [comment]
>Do you guys realize that if you want to do some operation in R, you need to pull it all into the local memory? 

The proposed problem does not need to work with 20 billion rows.

The logic will not reside in two places. It will be only in R.

I am able and happy to maintain my contributions to Achilles. In fact I am trying to add to that contribution.

Themis WG is targeting Achilles as the place where the logic will be. (to keep it simple for OMOP adopters)

**Comment by chrisknoll** [comment]
Just to be clear:

> I am proposing to allow 2 modes of Heel rules.
> 
> One in SQL (now) and one in R directly. (not used as of now)
> 
> We load some Achilles results data into memory (if it is small, under 50000 rows or so) - and do Heel logic in R.
> 

This sounds like that once we have logic in R, and if the results is < 50k rows, we do the Heel logic in R.  What is not clear is the 'else':  If it's more than that threshold, then we would leverage SQL?  @vojtechhuser : if that's the case, this sounds like the same Heel logic would be in 2 places.  So, I'd suggest you clarify your approach before we proceed with anything.

**Comment by vojtechhuser** [comment]
I think the multi threading change deserves a full version increase. (1.6? (as proposed by my draft release notes)

**Comment by vojtechhuser** [comment]
@chrisknoll  OK. Let me elaborate on the "else" problem.
Let's think about Heel and how it is managed. 
We have 42 rules (or so). Consider a new rule 43 or new rule 44 and so on...
When a new rule is created and quite often has associated measure (or derived measure) and this measure is checked against the threshold for that rule.

I am proposing that a new rule (e..g, 43 about allowable units for measurements) is either implemented in SQL or in R.

So each rule (as in rule_overview.csv) lives either in R or in SQL. So a new rule 43 logic uses R because parametized SQL may not be the best approach. 

We can add a column to the Rule overview file to track the implementation language. Just like we do for threshold.

This will allow management over time. R will allow to avoid SQLRender issues with multiple dialect where the whole problem fits easily in memory. (especially if it utilizes external knowledge base for which units are observed for which test (ThemisUnits study results) https://github.com/OHDSI/StudyProtocolSandbox/tree/master/NDCReview/extras/preliminary_results

**Comment by t-abdul-basser** [comment]
@vojtechhuser  I agree fully with that. I meant v1.6. Does Jun 1 work as a release date? 

@chrisknoll To be clear I like your idea as a compromise although I would prefer to continue with for now. one of its upsides it that it may allow us to do something similar--i.e. create a pluggable execution package--for the Python crowd as well.

**Comment by cgreich** [comment]
Friends. I can see both your arguments:

@chrisknoll and @t-abdul-basser: Keep it simple and use the existing SQL capabilities, it's made for this stuff.
@vojtechhuser: R is a much better mechanism for standardizing across SQL flavors, especially if we are torturing SQLRender with highly complex SQL, and once it is in memory you can do a whole lot of things.

I don't know. Appears to me that in the long run addition of R will benefit us, but not sure how much we should push it right now.

**Comment by t-abdul-basser** [comment]
@cgreich Thanks you. I think that we have a good forward plan: @vojtech and I will discuss @chrisknoll's @vojtechhuser's suggestion that we create pluggable R and SQL analysis/heel rules packages after the v1.6 release.

**Comment by alondhe** [comment]
For 2.0, using R to create parameterized analyses SQL will be a focus so that we aren't reviewing hundreds of queries -- just a smaller set of analysis templates. We also will need to identify SQL champions for each platform that can help with telling us what works and what doesnt (especially BigQuery, Impala, and Oracle). 

Still, SQL has to be used for the analyses. We may be able to use R for Heel, but that still requires pulling down the results tables locally.
