### ISSUE TITLE
Merge from my fork into MT-plus branch

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#294]
Hi @t-abdul-basser,

I think we have a versioning issue with the last merge you submitted. My alondhe-master branch was not actually the latest work I had for multithreading, I had switched over to using the MT-plus branch after my PR became under review.

Can we revert the MT-plus branch back?

Thanks,
Ajit

**Comment by t-abdul-basser** [comment]
Sure. I reached out by email to confirm your last commit.

**Comment by t-abdul-basser** [comment]
I created a new branch [mt-plus](https://github.com/OHDSI/Achilles/tree/mt-plus) from your [last commit](https://github.com/OHDSI/Achilles/tree/27e139d7731397b97448dec6db64435df9b10c9b) prior to my incorrect approval of PR #262 . (I deleted multithreaded-plus to avoid confusion.) I will start merge of this branch into master on the assumption that it contains all your commits unless you you tell me otherwise :).

**Comment by t-abdul-basser** [comment]
Correct commit identified.
