### ISSUE TITLE
Conform with CDMv6

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#333]
@t-abdul-basser and @vojtechhuser -- just FYI, I've been working on a cdm_v6 branch of Achilles to handle the changes in CDMv6:

1. Death table is removed, deaths are stored in Observation (observation_concept_id = 4306655), with person.death_datetime identifying the correct death event to use for analysis. Death causes are stored in condition_occurrence with a condition_type_concept_id that is in the 'Death Type' concept class.
2. Date fields everywhere (except for in cohort and observation_period) are now datetimes. 

My branch will use the analyses_v5 if the cdm version is 5.x, analyses_v6 if 6.x.

If you guys get a chance to review, let me know if you see any issues. I don't think we need to merge soon, but probably before year end.

**Comment by t-abdul-basser** [comment]
Thanks for the update  @alondhe  and for documenting this here. I am following your work on the cdm_v6 branch and do not have an issues to bring to your attention. Let's target 1.7 at earliest.

**Comment by alondhe** [comment]
Based on conversations with the OHDSI architecture team, we may not update OHDSI tools to use CDM v6 until fall 2019.

**Comment by rpeys** [comment]
Hi! Thanks for working on the v6 branch. I am using that branch and ran into an issue (detailed below). I believe it occurred because the file ./inst/sql/sql_server/analyses_v6/11.sql still references the DEATH table, which doesn't exist in v6. 

I had ran the single thread achilles function:
`achilles(connectionDetails, 
  cdmDatabaseSchema = "cdm_mini", 
  resultsDatabaseSchema="results_mini",
  scratchDatabaseSchema = "scratch_mini",
  numThreads = 1,
  sourceName = "My Source Name", 
  cdmVersion = "6.0",
  runHeel = TRUE,
  runCostAnalysis = FALSE)`
 
And encountered the following error, while it was "merging scratch Achilles tables:" `50%Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: relation "s_tmpach_11" does not exist Position: 4511`

**Comment by rpeys** [comment]
Come to think of it, maybe I was not using the v6 branch. Does including `cdmVersion = "6.0"` in the `achilles()` function call invoke the code from the cdm_v6 branch?

**Comment by jcabrerazuniga** [comment]
I have this problem if running the Docker container version of Achilles. I used:

docker run --rm --net=atlas_nw --name achillesserver -v /opt/atlas/achilles/output:/opt/app/output -e ACHILLES_SOURCE=DEFAULT -e ACHILLES_DB_URI=postgresql://postgres:SOMEPASSWORD@achillesdb:5432/ohdsi -e ACHILLES_CDM_SCHEMA=public -e ACHILLES_VOCAB_SCHEMA=public -e ACHILLES_RES_SCHEMA=public -e ACHILLES_CDM_VERSION=5   achilles_achilles

Are you going to update the code for the docker container so this problem will not show up?

**Comment by alondhe** [comment]
@jcabrerazuniga -- we don't have CDM v6 support, and won't until end of year. The v6 branch is not really active, so I wouldn't suggest using it.

**Comment by fdefalco** [comment]
Achilles only supports CDM v5.x at this time. CDM 6 will not be supported as the specification has gone unutilized in the community. Expect next version support with updated CDM v7 specification.
