### ISSUE TITLE
cdm_v6 error "ERROR: relation "results.cohort" does not exist"

### ISSUE THREAD

**Issue by rpeys** [OHDSI/Achilles#396]
When running Achilles for cdm v6 I keep running up against this error:

in output/log_achilles.txt it says:
```
Warning: file("") only supports open = "w+" and open = "w+b": using the former
Error in readChar(pathToSql, file.info(pathToSql)$size) :
  invalid 'nchars' argument
```

in errorReport.txt it says:
```
Error:
org.postgresql.util.PSQLException: ERROR: relation "results.cohort" does not exist
  Position: 16

SQL:
SELECT  * from results.cohort LIMIT 1;
```
 "results" is the name of my @resultsDatabaseSchema variable. so I traced this back to the line `sql <- SqlRender::renderSql("select top 1 * from @resultsDatabaseSchema.cohort;",` in R/Achilles.R

I cannot figure out why this is an issue - the cohort table indeed does not exist, but that line of sql in R/Achilles.R is wrapped in a try/catch, and should throw a warning not an error. Would appreciate help debugging! I am working off of the cdm_v6 branch on my personal fork - please look at that repo (https://github.com/rpeys/Achilles/tree/cdm_v6) as I had edited these lines in earlier commits, and perhaps that is causing a problem. Thank you!

**Comment by alondhe** [comment]
@rpeys this is actually a bit expected (but not ideal). When we test for the cohort table existing, although it is in a tryCatch block, DatabaseConnector still will create the errorReport.txt. So the code execution is fine, but you do get that text file regardless.

The main reason we used this approach for testing for a table's existence rather than using DatabaseConnector's getTableNames is because getTableNames doesn't work properly with Redshift.

**Comment by alondhe** [comment]
We should have a better way to check for the existence of the cohort table, or prevent the errorReport.txt file from being created in our current crude method.
