### ISSUE TITLE
results.achilles_results  doesn't exist

### ISSUE THREAD

**Issue by ATianmm** [OHDSI/Achilles#423]
when i run achiles, it report :
2019-09-10 02:47:31     [Main thread]   FATAL   DatabaseConnector       .createErrorReport      Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: relation "results.achilles_results" does not exist   Position: 624 An error report has been created at  /opt/app/errorReport.txt 

how can i solve this？

**Comment by alondhe** [comment]
It looks like the achilles function failed to execute, and then achillesHeel failed because the achilles_results table wasn't created.

Can you share your errorReport txt file?

**Comment by jcabrerazuniga** [comment]
I could not find any Reference on how/where to create the achilles_results table

**Comment by alondhe** [comment]
This error means that you have an analysis that failed. The achilles_results table is created only if all analyses complete. Can you post your log_achilles.txt file?

**Comment by jcabrerazuniga** [comment]
First I need to mention that I am running Achilles using Docker:

docker run --rm --net=atlas_nw --name achillesserver -v /opt/atlas/achilles/output:/opt/app/output -e ACHILLES_SOURCE=DEFAULT -e ACHILLES_DB_URI=postgresql://postgres:SOMEPASSWORD@achillesdb:5432/ohdsi -e ACHILLES_CDM_SCHEMA=public -e ACHILLES_VOCAB_SCHEMA=public -e ACHILLES_RES_SCHEMA=public -e ACHILLES_CDM_VERSION=5   achilles_achilles

Within my public schema I created all the tables I found at:

https://github.com/OHDSI/CommonDataModel/tree/master/PostgreSQL

and I got the next errors:
[log_achilles.txt](https://github.com/OHDSI/Achilles/files/3648465/log_achilles.txt)

Thanks for your assistance

**Comment by alondhe** [comment]
So it is erroring because you are using CDMv6, which Achilles does not support. For instance, we are looking for the death table which is in v5.3.1, but has been retired in v6 and moved to other tables.

I would recreate your data source to use CDM 5.3.1. The DDL is here: https://github.com/OHDSI/CommonDataModel/tree/v5.3.1.

**Comment by jcabrerazuniga** [comment]
Man, thanks a lot!! Please update Achilles page to show your link! Thx

**Comment by joaofonseca9** [comment]
Hi, sorry to reopen this issue but I am having the exact same error. In my case, the choice of v6 was on purpose since we are mapping PRO data that requires the survey occurrence table.

I have tried to give as argument the analysis IDs for those tables (death, episode) that don't exist in the CDM v6. But it feels like it is a void argument since it still performs those analysis
