### ISSUE TITLE
Issue with prevalence calculations in conditions, condition era and drug exposures

### ISSUE THREAD

**Issue by mdwalter** [OHDSI/Achilles#44]
We have been working on setting up Achilles for the first time and there are a few of the treemap graphs that don’t display. Tracing it back I believe it is due to the prevalence for each row (Conditions, Condition Era, Drug Exposures) being calculated at 0%. The other treemaps based on prevalence get calculated and displayed correctly.

Digging into the sql itself (e.g. sqlConditionTreemap.sql) I can run the sql directly and it brings back the correct results and prevalence calculations but the JSON files appear to incorrect prevalence calculations from the results of the SQL statements. Has something like this been seen before?

**Comment by chrisknoll** [comment]
Sounds like something related to the R serialization down to the JSON object.  When you say 'appear incorrect' does that mean wrong numbers or no numbers?

**Comment by mdwalter** [comment]
We are looking into the rendering of the JSON file next but admittedly I don't have much experience with R.

I should have been more specific with what I'm seeing. Here's an example:
The sqlConditionTreemap.sql returns a row with the following values:
percent_persons: 0.17589
records_per_Person: 2.11681

When viewing the table associated with the treemap through the web application that same row shows the following values:
Prevalence; 0.00%
Records per Person: 2.00

The JSON file created for the treemap is consistent with what is displayed on the web application.

**Comment by chrisknoll** [comment]
This looks like an integer rounding issue. I can't say that I've exactly seen this before but it does 'feel' familiar.  Basically somewhere along the line it's taking that 0.17 value and it's becoming an integer (0) then converted into a 2 precision float for percentage formatting (0.00).  I'm guessing this is the case because of what is happening with the 2.11 becoming 2.00.

**Comment by kboomhouwer** [comment]
Hi Chris,

We are also facing same issue and we found out the issue is with SQLRENDER. The Treemap SQLs which uses a round function with expression like "round(1.0*ar1.count_value / denom.count_value,5) as percent_persons" is translated as "ROUND(CAST(1.0*ar1.count_value / denom.count_value AS NUMERIC),5) as percent_persons"

Thing to notice here is CAST to NUMERIC is not specified with any precision and scale value. According to Redshift documentation here (http://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html1) when NUMERIC scale value is not specified it is by default set to zero.

This may require some change in either ACHILESE R package or in SQLRender package. Please suggest your thoughts on this.

**Comment by schuemie** [comment]
Lovely! In PostgreSQL it is the other way around: if you don't specify the precision, it will allow any type of precision (see [here](http://www.postgresql.org/docs/9.3/static/datatype-numeric.html)).

I've just changed NUMERIC to FLOAT for RedShift. Could you try updating SqlRender? Close all instances of R, open one instance of R, and do 
```r
devtools::install_github("ohdsi/SqlRender")
```
That should fix the problem.

FYI: the reason for the cast is that PostgreSQL and Redshift do not support all numeric types in their `round()` function and will cause a crash, even if it is easy to cast the numeric type to something that the function does accept.

**Comment by mdwalter** [comment]
Thanks for the update Schuemie. We redeployed the SqlRender component and it fixed the issue with the prevalence calculation.
