### ISSUE TITLE
Achilles rules and explanation

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/Achilles#452]
Hello Everyone,

I was trying to run Achilles on our CDM instance using the R code from github [here](https://github.com/OHDSI/Achilles)

I am able to see under "results.achilles_heel_results" that some of analysis have thrown errors and warnings.

1)  How can I take a look at the list of rules/checks that Achilles does? Is there any csv file which contains the list of rules/checks? Under github, I could find a vignette pdf but that doesn't have the rules.

**Example 1**

`ERROR: 406 - Distribution of age by condition_concept_id (count = 1361); min value should not be negative`

I guess this is about plotting age distribution for each condition_concept_id in our database. but am not sure what does `min value should not be negative` mean here? We have filled ZERO as concept_id for "unable to map items".

**Example 2**

`ERROR: 709-Number of drug exposure records with invalid person_id; count (n=14) should not be > 0`

But all our person_ids are valid. Meaning person_ids from cdm.drug_exposure table are also present in cdm.person table. So what does invalid person_id mean here?

Similarly, I see few more error messages with "invalid visit_id". What does invalid visit_id mean when the visit_ids are present in visit_occurrence and other domain tables.

**Example 3**

`ERROR: 810-Number of observation records outside valid observation period; count (n=8877) should not be > 0`

We have defined an observation_period of 1000 years. I understand this may not be possible in real life at all. But why does it still throw error as "outside valid observation period" when all our domain dates are within our observation_period. Is there any limit imposed anywhere for observation_period that we aren't aware of?

I would like to understand what these rules are and the location from where I can see all these rules/csv files? Is there any examples on this?

2)  Is it possible to know the records which violated the rules? I know for DQD, we have this option but is it possible for Achilles?

Can help us with this?

**Comment by alondhe** [comment]
Hi @SSMK-wq ,

The Achilles checks CSV is located here: https://github.com/OHDSI/Achilles/blob/master/inst/csv/achilles/achilles_analysis_details.csv.

Regarding your questions:

**Example 1**
This is saying you have conditions for patients that precede their birth; age is < 0.

**Example 2**
It seems to be finding person_ids in drug_exposure that are not in person. For reference, the query is located here: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/709.sql. Can you run the tweaked query below? Are there person_ids that show up?

(Keep in mind, you'll need to use SqlRender::render() to fill in the parameters, and SqlRender::translate() to translate to your SQL dialect)

`select de1.person_id from
	@cdmDatabaseSchema.drug_exposure de1
	left join @cdmDatabaseSchema.person p1
	on p1.person_id = de1.person_id
where p1.person_id is null`

**Example 3**
For reference, the query is located here: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/810.sql.

What happens when you run this tweaked version?

`select o1.PERSON_ID
from
	@cdmDatabaseSchema.observation o1
	left join @cdmDatabaseSchema.observation_period op1
	on op1.person_id = o1.person_id
	and o1.observation_date >= op1.observation_period_start_date
	and o1.observation_date <= op1.observation_period_end_date
where op1.person_id is null
`

For Achilles, the ability to find the violating records isn't as convenient as it is in DQD. You have to go to the SQL file as I showed above and then tweak the query to show the records rather than the counts.

**Comment by t-abdul-basser** [comment]
Thanks @alondhe !
