### ISSUE TITLE
Scratch vs Temp database schema 

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/Achilles#456]
Hello Everyone,

I recently came across OHDSI packages and tried running Achilles and PheValuator.

As I just followed the tutorials, I ran Achilles as is based on the tutorials.

Meaning I gave the `scratch database schema = scratch`

but in our database there is no schema like `scratch` instead it is `temp`.

But Achilles didn't throw any error? Doesn't Achilles use scratch schema at all during quality checks?

Whereas when I ran another OHDSI package called `PheValuator`, I was able to see that it threw error when I used `Scratch` as the value

When I modified it to `temp`, it worked fine.

Am I failing to understand something here?

**Comment by alondhe** [comment]
In Achilles, the scratchDatabaseSchema is used if you run the package with more than 1 thread. If you use only 1 thread, temp tables are used and the scratchDatabaseSchema value is ignored.

The reason we use a scratchDatabaseSchema in Achilles when using > 1 thread is because we use multiple concurrent SQL sessions before merging staging tables into the final tables. Temp tables live only within a particular SQL session and therefore we need to use actual staging tables in this case.

I can't speak for PheValuator as I've only used it once.
