### ISSUE TITLE
SQL Only option still requires connection to database (it should not)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#589]
all in the title

**Comment by vojtechhuser** [comment]
This is a problem for us because on host B - there is not internet but we can paste code created on host A. We need on host A (without the db connection) to generate the sql.  In the past, the sql only option worked fine.

**Comment by alondhe** [comment]
Pretty sure it's this block, which checks for the cohort table existence in order to determine if the analysis on that table should be conducted:

https://github.com/OHDSI/Achilles/blob/master/R/Achilles.R#L222-L246

I think it just needs to be modified to run only when sqlOnly is false. But also, I'm not really sure the cohort analyses add any value (1700 and 1701). I would suggest removing them.
