### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by moshe2590** [OHDSI/Achilles#643]
Hi all,
I try to connect my database via rstudio with the following code:

library(achilles)
connectionDetails <- createConnectionDetails(
dbms = "redshift",
server = "jdbc:resdhift://<url>:5439/<scheme name>,
user = "*",
password = "*",
port = "5439".
pathToDriver = "<pathToDriver>")

Achilles:achilles(connectionDetails = connectionDetails, cdmDatabaseSchema = "<cdmDatabaseSchema >",....)

The output is:
Connecting using Redshift driver
Error in loadJdbcDriver(driverCllass, classPath) :
java.lang.ClassNotFoundException

I validated that the driver jar file is in <pathToDriver>.

I would like to get help with this issue.

Thank you.

**Comment by AnthonyMolinaro** [comment]
Hi @moshe2590 ,

Since Achilles makes use of other packages in the OHDSI universe, we need to ensure those underlying packages are configured properly.  Please start with DatabaseConnector.  Please see the instructions [here](https://ohdsi.github.io/Hades/rSetup.html), [here](https://ohdsi.github.io/DatabaseConnector/), and [here](http://ohdsi.github.io/DatabaseConnector/articles/Connecting.html#obtaining-drivers).   Please ensure that you can connect to your database with DatabaseConnector and execute a simple query before using Achilles.  Once you have DatabaseConnector working, we can try to get Achilles running.
