### ISSUE TITLE
exportToJson fails on PDW

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Achilles#74]
This is due to the fact that we're mixing data types in the varchar() columns in ACHILLES_results. The fix is to use a different distribution for the analysis_id column in the table. This will be done via a change to SqlRender but noting the issue here so we can test it end-to-end.

**Comment by schuemie** [comment]
Could you elaborate on what the problem is? What goes wrong when DISTRIBUTION = REPLICATE?

I'd like to push back a bit on the current solution. SqlRender is supposed to be generic, but now it will have rules specific to Achilles, no idea what that will do to other applications (I already hate the rules for person_id and subject_id).

**Comment by chrisknoll** [comment]
There are 2 reasons:

Reason 1:
When we do a query for things like select cast(stratum_3 as int) where analysis_id = 108, the PDW actually wants to (for some ungodly reason) find all the rows, cast the stratum_3 as int, and then apply the where clause. The problem is that stratum_3 being the lovely varchar that it is, contains both numerics and text strings, where some can be casted into int, and others not (such as 'Below Average Range' as analysis 1818 give us).  When we partition the table by analysis_id, the where clause is, in fact, evaluated first, and then the casting happens.  stratum_3 is guaranteed to be an int for analysis 108.

Reason 2:
Achilles results is pretty hefty.  maybe a hundred gigs after it's all processed. Replicating this table means that we take up 32 * (several hundred gigs) space because we're replicating this table.  Better to have this data distributed across nodes.  

Alternative solution:
If we could provide hints in OHDSI sql as to the strategy of creating the table (using hash keys on table creates for PDW/Redshift for example), or other index strategies that could be applied to a table that would respond based on the dialect, that'd be great. Then we'd give a partition hint in the OHDSI sql and it would handle it that way, without keying on a column name (such as person_id, subject_id, and now analysis_id).  I'm not sure how brittle this would become.

Alternative, Althernative solution:
We start implementing dialect-specific overrides.

-Chris

**Comment by schuemie** [comment]
Ah, I just remembered running into reason 1 myself (I didn't know that having a different distribution would fix it). My solution was to first create a temp table to limit to the subset where we know the varchar will contain numbers, and then do the cast. Not sure how feasible that is in this situation.

I know we talked about the hints before. Either we
- Allow hints to be added inside comments, so SQL Server doesn't choke on them, or
- Also require translation for SQL Server (this is not that big a deal since we almost always also render, and there is less and less of a reason why those should be two steps)

Both will require some fundamental changes to SqlRender. Not something I can do in the short term.

For the dialect-specific overrides we have the structure in place, but in Achilles it will affect a large number of SQL scripts, so I would rather not go there.

**Comment by chrisknoll** [comment]
Yes, updating sql render to support hints is a huge shift, and something I'd like to really plan out how hints are scoped to specific blocks of sql, and would totally love to have that discussion when the time comes.  For the short term, our probelm with creating a temp table is the same issue that you raised with dialect specific sql:  too many changes to the SQL. Anywhere we're doing the cast(as int) to a stratum, we'd have to rewrite it to use the temp tables, then change the query to refer to the temp table.  It's everywhere, and so we found that hashing on analysis_id was the least invasive change that solved the problem.

-Chris
