### ISSUE TITLE
Issue with exportToJson() CDM ver.4, Redshift.

### ISSUE THREAD

**Issue by GlebMalikov** [OHDSI/Achilles#75]
I'm trying to export the results, calling exportToJson(). Some reports are extracted without the problems, but when it comes to Achilles Heel report, I get this error:

Generating achilles heel report
Generating measurement treemap
  |                                                                      |   0%Error in readChar(pathToSql, file.info(pathToSql)$size) :
  invalid 'nchars' argument
In addition: Warning message:
In file(con, "rb") :
  file("") only supports open = "w+" and open = "w+b": using the former
>

**Comment by chrisknoll** [comment]
I will look into this, but from the warning, it seems to be stemming from the parameter passed into file(), which is where the target file is speciried. Is it psosible that you have spaces in the path, or something else out of the ordinary in the parameters?  Could you give me the exact exportToJson() call you are making?  Also: there is an exportHeelToJson() call that you can use to call it directly, but it would be good to know why this is failing in the normal exportToJson, since they should be writing the output file to the same exact place.

-Chris

**Comment by chrisknoll** [comment]
This is fixed on master.  Please pull latest package (using install_git) to get latest changes. Let me know if you have any issues.

**Comment by GlebMalikov** [comment]
Reinstalled updated Achilles, now it works perfectly. Thank you very much!
